name: Cypress Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-22.04
   
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
     - name: install
       run: apt-get install -y libva-drm2 libva-x11-2 libva2

     - name: Run Cypress Test
       uses: cypress-io/github-action@v5
       env:
        ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'
       with:
         build: npm install cypress --save-dev
         command: npx cypress open

       
   
